// Interface text (menus, headings, labels) in three languages.
// Facts about the school are NOT here — they are in content/school.js.
// {name}-style placeholders are filled in by the templates.
// In Uzbek, a plain apostrophe is fine: o'quvchi → oʻquvchi at build time.

export const ui = {
  // ── Shared ────────────────────────────────────────────────────────────────
  'skip': { uz: "Asosiy mazmunga o'tish", ru: 'Перейти к основному содержанию', en: 'Skip to main content' },
  'nav.home': { uz: 'Bosh sahifa', ru: 'Главная', en: 'Home' },
  'nav.about': { uz: 'Maktab haqida', ru: 'О школе', en: 'About' },
  'nav.academics': { uz: "Ta'lim", ru: 'Обучение', en: 'Academics' },
  'nav.results': { uz: 'Natijalar', ru: 'Результаты', en: 'Results' },
  'nav.admissions': { uz: 'Qabul', ru: 'Поступление', en: 'Admissions' },
  'nav.news': { uz: 'Yangiliklar', ru: 'Новости', en: 'News' },
  'nav.contact': { uz: 'Aloqa', ru: 'Контакты', en: 'Contact' },
  'nav.profile': { uz: 'Maktab profili', ru: 'Профиль школы', en: 'School Profile' },
  'nav.main': { uz: 'Asosiy menyu', ru: 'Главное меню', en: 'Main menu' },
  'header.kicker': { uz: "Samarqand viloyati · O'zbekiston", ru: 'Самаркандская область · Узбекистан', en: 'Samarkand Region · Uzbekistan' },
  'header.menu': { uz: 'Menyu', ru: 'Меню', en: 'Menu' },
  'header.profileCta': { uz: 'Universitetlar uchun', ru: 'Для университетов', en: 'For universities' },
  'lang.label': { uz: 'Til', ru: 'Язык', en: 'Language' },

  'footer.blurb': {
    uz: "5–11-sinflarda matematika va tabiiy fanlar chuqurlashtirib o'qitiladigan, iqtidorli o'quvchilar uchun bepul davlat maktabi.",
    ru: 'Бесплатная государственная школа для одарённых учеников 5–11 классов с углублённым изучением математики и естественных наук.',
    en: 'A tuition-free state school for gifted students in grades 5–11, with in-depth mathematics and natural sciences.',
  },
  'footer.pages': { uz: "Bo'limlar", ru: 'Разделы', en: 'Pages' },
  'footer.contact': { uz: 'Aloqa', ru: 'Контакты', en: 'Contact' },
  'footer.official': { uz: 'Rasmiy manbalar', ru: 'Официальные ресурсы', en: 'Official resources' },
  'footer.piima': { uz: 'PIIMA rasmiy sayti', ru: 'Официальный сайт PIIMA', en: 'PIIMA official website' },
  'footer.portal': { uz: 'Qabul portali — ariza.piima.uz', ru: 'Портал приёма — ariza.piima.uz', en: 'Admissions portal — ariza.piima.uz' },
  'footer.updated': { uz: "So'nggi yangilanish: {date}", ru: 'Последнее обновление: {date}', en: 'Last updated: {date}' },

  'draft.missing': { uz: "Ma'lumot kerak", ru: 'Нужны данные', en: 'Needs information' },
  'draft.draft': { uz: 'Qoralama — tasdiqlang', ru: 'Черновик — подтвердите', en: 'Draft — please confirm' },
  'draft.verify': { uz: 'Tekshiring', ru: 'Проверьте', en: 'Please check' },
  'draft.banner': {
    uz: "QORALAMA: rangli belgilar maktab tasdiqlashi yoki taqdim etishi kerak bo'lgan ma'lumotlarni ko'rsatadi. Ular e'lon qilinadigan saytda ko'rinmaydi.",
    ru: 'ЧЕРНОВИК: цветные отметки показывают сведения, которые школа должна подтвердить или предоставить. На опубликованном сайте их нет.',
    en: 'DRAFT PREVIEW: coloured marks show information the school still has to confirm or provide. They do not appear on the published site.',
  },

  'common.readMore': { uz: 'Batafsil', ru: 'Подробнее', en: 'Read more' },
  'common.classOf': { uz: '{year}-yil bitiruvchilari', ru: 'Выпуск {year} года', en: 'Class of {year}' },
  'country.USA': { uz: 'AQSh', ru: 'США', en: 'USA' },
  'country.Uzbekistan': { uz: "O'zbekiston", ru: 'Узбекистан', en: 'Uzbekistan' },

  // ── Fact labels ───────────────────────────────────────────────────────────
  'fact.type': { uz: 'Turi', ru: 'Тип', en: 'Type' },
  'fact.network': { uz: 'Tizim', ru: 'Система', en: 'School system' },
  'fact.networkValue': { uz: 'PIIMA ixtisoslashtirilgan maktablari', ru: 'Специализированные школы PIIMA', en: 'PIIMA specialized schools' },
  'fact.founded': { uz: 'Tashkil etilgan', ru: 'Год основания', en: 'Founded' },
  'fact.location': { uz: 'Joylashuvi', ru: 'Расположение', en: 'Location' },
  'fact.grades': { uz: 'Sinflar', ru: 'Классы', en: 'Grades' },
  'fact.students': { uz: "O'quvchilar soni", ru: 'Число учащихся', en: 'Students' },
  'fact.teachers': { uz: "O'qituvchilar soni", ru: 'Число учителей', en: 'Teachers' },
  'fact.classSize': { uz: 'Sinf hajmi', ru: 'Наполняемость классов', en: 'Class size' },
  'fact.classSizeValue': { uz: "{n} nafargacha o'quvchi", ru: 'не более {n} учеников', en: 'No more than {n} students' },
  'fact.language': { uz: "Ta'lim tili", ru: 'Язык обучения', en: 'Language of instruction' },
  'fact.tuition': { uz: "O'qish haqi", ru: 'Стоимость обучения', en: 'Tuition' },
  'fact.tuitionValue': { uz: 'Bepul — davlat hisobidan', ru: 'Бесплатно — за счёт государства', en: 'Free — funded by the state' },
  'fact.admission': { uz: 'Qabul', ru: 'Приём', en: 'Admission' },
  'fact.admissionValue': { uz: 'Tanlov asosidagi kirish imtihonlari', ru: 'Конкурсные вступительные экзамены', en: 'Competitive entrance examinations' },
  'fact.ceeb': { uz: 'CEEB kodi', ru: 'Код CEEB', en: 'CEEB code' },
  'fact.address': { uz: 'Manzil', ru: 'Адрес', en: 'Address' },
  'fact.postal': { uz: 'Pochta indeksi', ru: 'Почтовый индекс', en: 'Postal code' },
  'fact.phone': { uz: 'Telefon', ru: 'Телефон', en: 'Phone' },
  'fact.email': { uz: 'Elektron pochta', ru: 'Эл. почта', en: 'Email' },
  'fact.website': { uz: 'Veb-sayt', ru: 'Сайт', en: 'Website' },
  'fact.hours': { uz: 'Ish vaqti', ru: 'Часы работы', en: 'Office hours' },

  // ── Home ──────────────────────────────────────────────────────────────────
  'home.eyebrow': { uz: 'Bepul davlat maktabi · 5–11-sinflar', ru: 'Бесплатная государственная школа · 5–11 классы', en: 'Tuition-free state school · Grades 5–11' },
  'home.title': {
    uz: "Iqtidorli o'quvchilar uchun chuqurlashtirilgan matematika va tabiiy fanlar",
    ru: 'Углублённая математика и естественные науки для одарённых учеников',
    en: 'In-depth mathematics and science for gifted students',
  },
  'home.lead': {
    uz: "O'quvchilar tanlov asosidagi kirish imtihonlari orqali qabul qilinadi va 5-sinfdan boshlab matematika, fizika, kimyo va biologiyani chuqur o'rganadi. Har bir sinfda {n} nafardan ko'p o'quvchi bo'lmaydi.",
    ru: 'Учеников принимают по результатам конкурсных вступительных экзаменов. С 5 класса они углублённо изучают математику, физику, химию и биологию. В классе — не более {n} учеников.',
    en: 'Students are admitted through a competitive entrance examination and study mathematics, physics, chemistry and biology in depth from grade 5. No class has more than {n} students.',
  },
  'home.ctaProfile': { uz: 'Universitetlar uchun maktab profili', ru: 'Профиль школы для университетов', en: 'School Profile for universities' },
  'home.ctaAdmissions': { uz: "Qabul qanday o'tadi", ru: 'Как поступить', en: 'How to apply' },
  'home.glance': { uz: 'Qisqacha', ru: 'Коротко о школе', en: 'At a glance' },
  'home.glanceGrades': { uz: 'Sinflar', ru: 'Классы', en: 'Grades' },
  'home.glanceClass': { uz: "Sinfdagi o'quvchilar soni — ko'pi bilan", ru: 'Учеников в классе — не более', en: 'Students per class, at most' },
  'home.glanceFreeValue': { uz: 'Bepul', ru: 'Бесплатно', en: 'Free' },
  'home.glanceFreeLabel': { uz: "Ta'lim davlat hisobidan", ru: 'Обучение за счёт государства', en: 'Tuition — paid by the state' },
  'home.glanceCert': {
    uz: "{year}-yil bitiruvchilaridan xalqaro yoki milliy sertifikatga ega bo'lganlar",
    ru: 'Выпускники {year} года с международными или национальными сертификатами',
    en: 'Class of {year} graduates with international or national certificates',
  },
  'home.focusEyebrow': { uz: 'Ixtisoslik', ru: 'Специализация', en: 'Specialization' },
  'home.focusTitle': { uz: "Chuqurlashtirib o'qitiladigan fanlar", ru: 'Что мы изучаем углублённо', en: 'What we teach in depth' },
  'home.missionEyebrow': { uz: 'Maqsadimiz', ru: 'Наша миссия', en: 'Our mission' },
  'home.resultsEyebrow': { uz: 'Natijalar', ru: 'Результаты', en: 'Results' },
  'home.resultsCertified': {
    uz: "{total} nafar bitiruvchidan {n} nafari IELTS va SAT kabi xalqaro yoki milliy sertifikatlarga ega",
    ru: '{n} из {total} выпускников имеют международные или национальные сертификаты, такие как IELTS и SAT',
    en: '{n} of {total} graduates hold international or national certificates such as IELTS and SAT',
  },
  'home.resultsTop': { uz: 'Eng yuqori natijalar', ru: 'Лучшие результаты', en: 'Top reported scores' },
  'home.resultsOffers': { uz: 'Qabul takliflari olingan universitetlar', ru: 'Предложения о зачислении от университетов', en: 'Offers of admission from' },
  'home.resultsLink': { uz: 'Barcha natijalar', ru: 'Все результаты', en: 'All results' },
  'home.uniEyebrow': { uz: 'Universitetlar uchun', ru: 'Для университетов', en: 'For universities' },
  'home.uniTitle': { uz: 'Qabul komissiyalari uchun maktab profili', ru: 'Профиль школы для приёмных комиссий', en: 'A School Profile for admissions officers' },
  'home.uniText': {
    uz: "Maktab profili o'quv dasturi, baholash tizimi va bitiruvchilar natijalarini bitta sahifada jamlaydi. Uni chop etish yoki PDF sifatida saqlash mumkin.",
    ru: 'Профиль школы собирает на одной странице учебную программу, систему оценивания и результаты выпускников. Его можно распечатать или сохранить в PDF.',
    en: 'The School Profile sums up our curriculum, grading scale and graduate results on one page that can be printed or saved as a PDF.',
  },
  'home.uniCta': { uz: 'Maktab profilini ochish', ru: 'Открыть профиль школы', en: 'Open the School Profile' },
  'home.familyEyebrow': { uz: 'Ota-onalar uchun', ru: 'Для родителей', en: 'For families' },
  'home.familyTitle': { uz: 'Qabul faqat rasmiy portal orqali', ru: 'Приём — только через официальный портал', en: 'Admission only through the official portal' },
  'home.familyText': {
    uz: "Arizalar faqat PIIMA portali — ariza.piima.uz orqali qabul qilinadi. Ta'lim bepul, maktab arizalarni to'g'ridan-to'g'ri qabul qilmaydi.",
    ru: 'Заявления принимаются только через портал PIIMA — ariza.piima.uz. Обучение бесплатное, школа не принимает заявления напрямую.',
    en: 'Applications are accepted only through the PIIMA portal, ariza.piima.uz. Education is free, and the school does not accept applications directly.',
  },
  'home.familyCta': { uz: 'Qabul haqida batafsil', ru: 'Подробнее о приёме', en: 'How admission works' },
  'home.newsTitle': { uz: "So'nggi yangiliklar", ru: 'Последние новости', en: 'Latest news' },

  // ── About ─────────────────────────────────────────────────────────────────
  'about.title': { uz: 'Maktab haqida', ru: 'О школе', en: 'About the school' },
  'about.missionTitle': { uz: 'Maqsadimiz', ru: 'Наша миссия', en: 'Our mission' },
  'about.factsTitle': { uz: 'Raqamlar va faktlar', ru: 'Факты и цифры', en: 'Facts and figures' },
  'about.leadershipTitle': { uz: "Rahbariyat va mas'ul shaxslar", ru: 'Руководство и контакты', en: 'Leadership and key contacts' },
  'about.teachersTitle': { uz: "O'qituvchilar", ru: 'Учителя', en: 'Teachers' },
  'about.facilitiesTitle': { uz: 'Moddiy-texnik baza', ru: 'Инфраструктура', en: 'Facilities' },
  'about.networkTitle': { uz: 'PIIMA tizimi', ru: 'Система PIIMA', en: 'The PIIMA system' },
  'about.networkText': {
    uz: "Maktab PIIMA tizimidagi ixtisoslashtirilgan maktablardan biri. Qabul, kirish imtihonlari va kvotalar PIIMA tomonidan markazlashgan tartibda tashkil etiladi.",
    ru: 'Школа входит в систему специализированных школ PIIMA. Приём, вступительные экзамены и квоты организуются PIIMA централизованно.',
    en: 'The school is one of the specialized schools in the PIIMA system. Admission, entrance examinations and quotas are organized centrally by PIIMA.',
  },
  'about.networkLink': { uz: "piima.uz saytiga o'tish", ru: 'Перейти на piima.uz', en: 'Visit piima.uz' },

  // ── Academics ─────────────────────────────────────────────────────────────
  'academics.title': { uz: "Ta'lim", ru: 'Обучение', en: 'Academics' },
  'academics.lead': {
    uz: "5–11-sinflar uchun matematika va tabiiy fanlarga yo'naltirilgan chuqurlashtirilgan dastur.",
    ru: 'Углублённая программа по математике и естественным наукам для 5–11 классов.',
    en: 'An in-depth program in mathematics and the natural sciences for grades 5–11.',
  },
  'academics.systemTitle': { uz: "Ta'lim tizimidagi o'rni", ru: 'Место в системе образования', en: 'Place in the national system' },
  'academics.systemText': {
    uz: "O'zbekistonda maktab ta'limi 11 yil davom etadi (1–11-sinflar). Maktabimizda 5–11-sinf o'quvchilari tahsil oladi.",
    ru: 'Школьное образование в Узбекистане длится 11 лет (1–11 классы). В нашей школе учатся ученики 5–11 классов.',
    en: 'School education in Uzbekistan lasts 11 years (grades 1–11). Our school teaches grades 5–11.',
  },
  'academics.specialTitle': { uz: 'Ixtisoslik fanlari', ru: 'Профильные предметы', en: 'Specialized subjects' },
  'academics.curriculumTitle': { uz: "O'quv rejasi", ru: 'Учебный план', en: 'Curriculum' },
  'academics.curriculumCaption': {
    uz: "Fanlar bo'yicha haftalik dars soatlari (sinflar kesimida)",
    ru: 'Количество уроков в неделю по предметам и классам',
    en: 'Weekly lessons per subject, by grade',
  },
  'academics.subject': { uz: 'Fan', ru: 'Предмет', en: 'Subject' },
  'academics.grade': { uz: 'Sinf', ru: 'Класс', en: 'Grade' },
  'academics.advanced': { uz: 'Chuqurlashtirilgan fan', ru: 'Углублённый предмет', en: 'In-depth subject' },
  'academics.gradingTitle': { uz: 'Baholash tizimi', ru: 'Система оценивания', en: 'Assessment and grading' },
  'academics.mark': { uz: 'Baho', ru: 'Оценка', en: 'Grade' },
  'academics.meaning': { uz: "Ma'nosi", ru: 'Значение', en: 'Meaning' },
  'academics.us': { uz: 'AQShdagi taxminiy muqobili', ru: 'Примерный эквивалент в США', en: 'Approx. US equivalent' },
  'academics.rankTitle': { uz: "O'rtacha ball (GPA) va reyting", ru: 'Средний балл (GPA) и рейтинг', en: 'GPA and class rank' },
  'academics.calendarTitle': { uz: "O'quv yili", ru: 'Учебный год', en: 'School year' },
  'academics.graduationTitle': { uz: 'Bitiruv', ru: 'Выпуск', en: 'Graduation' },
  'academics.examsTitle': { uz: 'Xalqaro imtihonlar', ru: 'Международные экзамены', en: 'International exams' },
  'academics.competitionsTitle': { uz: 'Olimpiadalar va tanlovlar', ru: 'Олимпиады и конкурсы', en: 'Olympiads and competitions' },
  'academics.activitiesTitle': { uz: 'Darsdan tashqari faoliyat', ru: 'Внеурочная деятельность', en: 'Beyond the classroom' },
  'academics.notOfferedTitle': { uz: "Maktabda mavjud bo'lmagan dasturlar", ru: 'Программы, которых нет в школе', en: 'Programs not offered' },

  // ── Results ───────────────────────────────────────────────────────────────
  'results.title': { uz: 'Natijalar', ru: 'Результаты', en: 'Results' },
  'results.lead': {
    uz: "Bitiruvchilar natijalari, imtihon ko'rsatkichlari va olimpiadalardagi yutuqlar.",
    ru: 'Результаты выпускников, экзаменов и олимпиад.',
    en: 'Graduate outcomes, exam results and competition awards.',
  },
  'results.graduates': { uz: 'Bitiruvchilar', ru: 'Выпускников', en: 'Graduates' },
  'results.certified': {
    uz: 'Xalqaro yoki milliy sertifikatga ega (IELTS, SAT va boshqalar)',
    ru: 'С международными или национальными сертификатами (IELTS, SAT и др.)',
    en: 'With international or national certificates (IELTS, SAT, etc.)',
  },
  'results.continuing': { uz: "Oliy ta'limda o'qishni davom ettirdi", ru: 'Продолжили обучение в вузах', en: 'Continued to higher education' },
  'results.scoresTitle': { uz: 'Tanlangan imtihon natijalari', ru: 'Отдельные результаты экзаменов', en: 'Selected test results' },
  'results.scoresNote': {
    uz: "Maktab e'lon qilgan natijalar; barcha imtihon topshirganlarning to'liq ro'yxati emas.",
    ru: 'Результаты, опубликованные школой; это не полный список всех сдававших.',
    en: 'Scores published by the school; not a complete list of all test-takers.',
  },
  'results.ielts': { uz: 'IELTS (umumiy ball)', ru: 'IELTS (общий балл)', en: 'IELTS (overall band)' },
  'results.sat': { uz: 'SAT (umumiy ball)', ru: 'SAT (общий балл)', en: 'SAT (total score)' },
  'results.statsTitle': { uz: 'Barcha imtihon topshirganlar', ru: 'Все сдававшие', en: 'All test-takers' },
  'results.offersTitle': { uz: 'Qabul takliflari', ru: 'Предложения о зачислении', en: 'Offers of admission' },
  'results.offersNote': {
    uz: '{year}-yil bitiruvchilariga qabul taklifini bergan universitetlar (tanlangan).',
    ru: 'Университеты, предложившие места выпускникам {year} года (выборочно).',
    en: 'Universities that offered places to members of the Class of {year} (selected).',
  },
  'results.destinationsTitle': { uz: "Bitiruvchilar o'qishga kirgan oliygohlar", ru: 'Куда поступили выпускники', en: 'Where graduates enrolled' },
  'results.privacy': {
    uz: "Natijalar o'quvchilarning ism-shariflarisiz e'lon qilinadi. Shaxsiy yutuqlar faqat o'quvchi (va ota-onasi) roziligi bilan e'lon qilinadi.",
    ru: 'Мы публикуем результаты без имён учеников. Личные достижения публикуются только с согласия ученика (и родителей).',
    en: 'We publish results without students’ names. Individual achievements are shared only with the consent of the student (and a parent).',
  },

  // ── Admissions ────────────────────────────────────────────────────────────
  'admissions.title': { uz: 'Qabul', ru: 'Поступление', en: 'Admissions' },
  'admissions.lead': { uz: "Maktabimizga qanday o'qishga kirish mumkin.", ru: 'Как поступить в нашу школу.', en: 'How to join our school.' },
  'admissions.noticeTitle': { uz: 'Faqat rasmiy portal orqali', ru: 'Только через официальный портал', en: 'Apply only through the official portal' },
  'admissions.notice': {
    uz: "Arizalar faqat PIIMA rasmiy portali — ariza.piima.uz orqali qabul qilinadi. Maktab arizalarni to'g'ridan-to'g'ri qabul qilmaydi, ta'lim esa bepul.",
    ru: 'Заявления принимаются только через официальный портал PIIMA — ariza.piima.uz. Школа не принимает заявления напрямую, а обучение бесплатное.',
    en: 'Applications are accepted only through the official PIIMA portal, ariza.piima.uz. The school does not accept applications directly, and education is free.',
  },
  'admissions.fraud': {
    uz: "O'rinlar faqat rasmiy tanlov natijasida beriladi. Pul evaziga qabulni «kafolatlaydigan» takliflarga ishonmang.",
    ru: 'Места распределяются только по итогам официального конкурса. Не доверяйте тем, кто «гарантирует» поступление за деньги.',
    en: 'Places are awarded only through the official competition. Do not trust anyone who offers to “guarantee” a place for money.',
  },
  'admissions.whoTitle': { uz: 'Kimlar ariza topshira oladi', ru: 'Кто может поступать', en: 'Who can apply' },
  'admissions.free': { uz: "Ta'lim bepul, qabul uchun to'lov olinmaydi.", ru: 'Обучение бесплатное, плата за поступление не взимается.', en: 'Education is free, and there is no admission fee.' },
  'admissions.classSize': { uz: "Har bir sinfda {n} nafardan ko'p o'quvchi bo'lmaydi.", ru: 'В каждом классе — не более {n} учеников.', en: 'Each class has no more than {n} students.' },
  'admissions.examsTitle': { uz: 'Kirish imtihonlari', ru: 'Вступительные экзамены', en: 'Entrance examinations' },
  'admissions.stepsTitle': { uz: 'Qabul bosqichlari', ru: 'Этапы приёма', en: 'How it works' },
  'admissions.step1': { uz: "ariza.piima.uz portalida ro'yxatdan o'ting va ariza topshiring.", ru: 'Зарегистрируйтесь на портале ariza.piima.uz и подайте заявление.', en: 'Register on ariza.piima.uz and submit an application.' },
  'admissions.step2': { uz: 'Kerakli hujjatlarni taqdim eting.', ru: 'Предоставьте необходимые документы.', en: 'Provide the required documents.' },
  'admissions.step3': { uz: "PIIMA tomonidan o'tkaziladigan kirish imtihonlarida qatnashing.", ru: 'Сдайте вступительные экзамены, которые проводит PIIMA.', en: 'Sit the entrance examinations organized by PIIMA.' },
  'admissions.step4': {
    uz: "Natijalar PIIMA portalida e'lon qilinadi; o'qish sentabr oyida boshlanadi.",
    ru: 'Результаты публикуются на портале PIIMA; занятия начинаются в сентябре.',
    en: 'Results are published on the PIIMA portal, and lessons start in September.',
  },
  'admissions.datesTitle': { uz: 'Muddatlar', ru: 'Сроки', en: 'Dates' },
  'admissions.docsTitle': { uz: 'Kerakli hujjatlar', ru: 'Необходимые документы', en: 'Documents' },
  'admissions.docsNote': {
    uz: "Ariza topshirishdan oldin portaldagi amaldagi ro'yxatni albatta tekshiring.",
    ru: 'Перед подачей заявления обязательно сверьтесь с актуальным списком на портале.',
    en: 'Always check the current list on the portal before applying.',
  },
  'admissions.faqTitle': { uz: "Ko'p beriladigan savollar", ru: 'Частые вопросы', en: 'Frequently asked questions' },
  'admissions.ctaTitle': { uz: 'Arizani PIIMA portalida topshiring', ru: 'Подайте заявление на портале PIIMA', en: 'Apply on the PIIMA portal' },
  'admissions.cta': { uz: "ariza.piima.uz saytiga o'tish", ru: 'Перейти на ariza.piima.uz', en: 'Go to ariza.piima.uz' },

  // ── News ──────────────────────────────────────────────────────────────────
  'news.title': { uz: 'Yangiliklar', ru: 'Новости', en: 'News' },
  'news.lead': { uz: "Maktab hayotidagi yangiliklar va e'lonlar.", ru: 'Новости и объявления школы.', en: 'News and announcements from the school.' },
  'news.back': { uz: 'Barcha yangiliklar', ru: 'Все новости', en: 'All news' },

  // ── Contact ───────────────────────────────────────────────────────────────
  'contact.title': { uz: 'Aloqa', ru: 'Контакты', en: 'Contact' },
  'contact.lead': { uz: "Maktab bilan bog'lanish uchun ma'lumotlar.", ru: 'Как связаться со школой.', en: 'How to reach the school.' },
  'contact.social': { uz: 'Ijtimoiy tarmoqlar', ru: 'Соцсети', en: 'Social media' },
  'contact.map': { uz: 'Xarita', ru: 'Карта', en: 'Map' },
  'contact.openYandex': { uz: 'Yandex Xaritalarda ochish', ru: 'Открыть в Яндекс Картах', en: 'Open in Yandex Maps' },
  'contact.openGoogle': { uz: 'Google Xaritalarda ochish', ru: 'Открыть в Google Картах', en: 'Open in Google Maps' },
  'contact.mapTitle': { uz: 'Maktab joylashgan joy xaritada', ru: 'Расположение школы на карте', en: 'Map showing the school’s location' },
  'contact.uniTitle': { uz: 'Universitetlar uchun', ru: 'Для университетов', en: 'For universities' },
  'contact.uniText': {
    uz: "Attestat, tavsiyanoma yoki o'quvchining maktabda o'qishini tasdiqlash uchun murojaat qiling:",
    ru: 'Для подтверждения аттестата, рекомендации или факта обучения обращайтесь:',
    en: 'To verify a transcript, a recommendation or enrolment, please contact:',
  },
  'contact.uniFallback': {
    uz: 'Attestat yoki tavsiyanomalarni tasdiqlash uchun maktabning elektron pochtasiga yozing: {email}.',
    ru: 'Для подтверждения аттестатов и рекомендаций напишите на почту школы: {email}.',
    en: 'To verify transcripts or recommendations, please email the school at {email}.',
  },
  'contact.admTitle': { uz: "Qabul bo'yicha savollar", ru: 'Вопросы о поступлении', en: 'Questions about admission' },
  'contact.admText': {
    uz: "Qabul PIIMA tomonidan ariza.piima.uz portali orqali o'tkaziladi. Umumiy savollar bo'yicha maktabga qo'ng'iroq qiling yoki yozing.",
    ru: 'Приём проводит PIIMA через портал ariza.piima.uz. По общим вопросам звоните или пишите в школу.',
    en: 'Admission is run by PIIMA through ariza.piima.uz. For general questions, call or write to the school.',
  },

  // ── School Profile ────────────────────────────────────────────────────────
  'profile.title': { uz: 'Maktab profili', ru: 'Профиль школы', en: 'School Profile' },
  'profile.subtitle': {
    uz: "Universitetlarning qabul komissiyalari uchun · {year} o'quv yili",
    ru: 'Для приёмных комиссий университетов · {year} учебный год',
    en: 'For university admissions officers · {year}',
  },
  'profile.print': { uz: 'Chop etish yoki PDF sifatida saqlash', ru: 'Распечатать или сохранить в PDF', en: 'Print or save as PDF' },
  'profile.intro': {
    uz: "Ushbu profil o'quvchilarimizning attestat va tavsiyanomalariga ilova qilinadi. Unda maktab, o'quv dasturi, baholash tizimi va so'nggi natijalar haqida ma'lumot berilgan.",
    ru: 'Этот профиль прилагается к аттестатам и рекомендациям наших учеников. В нём описаны школа, учебная программа, система оценивания и последние результаты.',
    en: 'This profile accompanies our students’ transcripts and recommendations. It describes the school, its curriculum and grading, and recent results.',
  },
  'profile.overviewTitle': { uz: "Umumiy ma'lumot", ru: 'О школе', en: 'Overview' },
  'profile.factsTitle': { uz: 'Asosiy faktlar', ru: 'Основные факты', en: 'Key facts' },
  'profile.curriculumTitle': { uz: "O'quv dasturi", ru: 'Учебная программа', en: 'Curriculum' },
  'profile.gradingTitle': { uz: 'Baholash', ru: 'Оценивание', en: 'Grading' },
  'profile.graduationTitle': { uz: 'Bitiruv talablari', ru: 'Требования к выпуску', en: 'Graduation requirements' },
  'profile.contactsTitle': { uz: "Aloqa ma'lumotlari", ru: 'Контакты', en: 'Contacts' },
  'profile.updated': { uz: 'Profil yangilangan sana: {date}', ru: 'Профиль обновлён: {date}', en: 'Profile updated: {date}' },

  // ── 404 ───────────────────────────────────────────────────────────────────
  'notfound.title': { uz: 'Sahifa topilmadi', ru: 'Страница не найдена', en: 'Page not found' },
  'notfound.text': {
    uz: "Siz qidirgan sahifa mavjud emas yoki ko'chirilgan.",
    ru: 'Страница, которую вы ищете, не существует или была перемещена.',
    en: 'The page you are looking for does not exist or has moved.',
  },
  'notfound.home': { uz: 'Bosh sahifaga qaytish', ru: 'На главную', en: 'Go to the home page' },

  // ── Search-engine descriptions (≈150 characters) ─────────────────────────
  'meta.home': {
    uz: "Urgut tumani ixtisoslashtirilgan maktabi — 5–11-sinflarda matematika va tabiiy fanlar chuqurlashtirib o'qitiladigan bepul davlat maktabi (Samarqand viloyati).",
    ru: 'Ургутская специализированная школа — бесплатная государственная школа с углублённым изучением математики и естественных наук для 5–11 классов (Самаркандская область).',
    en: 'Urgut Specialized School — a tuition-free state school in Samarkand Region, Uzbekistan, with in-depth mathematics and natural sciences for grades 5–11.',
  },
  'meta.about': {
    uz: "Maktab haqida: maqsad, faktlar va raqamlar, rahbariyat, o'qituvchilar va moddiy-texnik baza.",
    ru: 'О школе: миссия, факты и цифры, руководство, учителя и инфраструктура.',
    en: 'About Urgut Specialized School: mission, facts and figures, leadership, teachers and facilities.',
  },
  'meta.academics': {
    uz: "O'quv dasturi, ixtisoslik fanlari, baholash tizimi, o'quv yili va bitiruv talablari.",
    ru: 'Учебная программа, профильные предметы, система оценивания, учебный год и требования к выпуску.',
    en: 'Curriculum, specialized subjects, grading scale, school year and graduation requirements.',
  },
  'meta.results': {
    uz: "Bitiruvchilar natijalari: sertifikatlar, IELTS va SAT, universitetlardan qabul takliflari va olimpiadalar.",
    ru: 'Результаты выпускников: сертификаты, IELTS и SAT, предложения о зачислении от университетов и олимпиады.',
    en: 'Graduate results: certificates, IELTS and SAT scores, university offers and olympiad awards.',
  },
  'meta.admissions': {
    uz: "Maktabga qabul: faqat ariza.piima.uz orqali, bepul. Imtihonlar, muddatlar, hujjatlar va savollar.",
    ru: 'Поступление: только через ariza.piima.uz, бесплатно. Экзамены, сроки, документы и частые вопросы.',
    en: 'Admission: only through ariza.piima.uz, free of charge. Exams, dates, documents and frequently asked questions.',
  },
  'meta.news': { uz: "Maktab yangiliklari va e'lonlari.", ru: 'Новости и объявления школы.', en: 'News and announcements from Urgut Specialized School.' },
  'meta.contact': {
    uz: 'Manzil, telefon, elektron pochta, ijtimoiy tarmoqlar va xarita.',
    ru: 'Адрес, телефон, эл. почта, соцсети и карта.',
    en: 'Address, phone, email, social media and map.',
  },
  'meta.profile': {
    uz: "Universitetlarning qabul komissiyalari uchun maktab profili: o'quv dasturi, baholash va bitiruvchilar natijalari.",
    ru: 'Профиль школы для приёмных комиссий университетов: программа, оценивание и результаты выпускников.',
    en: 'School Profile for university admissions officers: curriculum, grading and graduate results.',
  },
};
