// Lists every fact in content/school.js that is still missing, a draft, or
// should be double-checked (see src/lib/facts.js for the markers).
//
//   npm run check       print the list
//   npm run checklist   also write CONTENT-CHECKLIST.md (to share with the school)
import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { school } from '../content/school.js';
import { news } from '../content/news.js';
import { collectFacts, factState } from '../src/lib/facts.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const GROUPS = [
  { state: 'todo', title: 'Missing', hint: 'Not shown on the site until someone fills it in.' },
  { state: 'draft', title: 'Drafts to confirm', hint: 'Suggested text. Shown only in draft builds (npm run dev), never on the live site, until the draft() wrapper is removed.' },
  { state: 'verify', title: 'To double-check', hint: 'Taken from the old website and published. Confirm it, then remove the verify() wrapper.' },
];

// "leadership.0.person" -> "leadership[director].person", so a path points at
// something a person can find in content/school.js.
function readablePath(root, path) {
  let node = root;
  return path
    .split('.')
    .map((key) => {
      if (factState(node) !== 'ok') node = node.value;
      const item = node?.[key];
      const label = Array.isArray(node) && item && typeof item === 'object' ? `[${item.id ?? item.year ?? key}]` : `.${key}`;
      node = item;
      return label;
    })
    .join('')
    .replace(/^\./, '');
}

// Short English preview of a draft/verify value.
function preview(value) {
  if (value == null) return '';
  if (typeof value !== 'object') return String(value);
  if (typeof value.en === 'string') return value.en;
  if (Array.isArray(value)) return `${value.length} item${value.length === 1 ? '' : 's'}`;
  return '';
}

const sources = [
  { file: 'content/school.js', root: school },
  { file: 'content/news.js', root: news },
];

const facts = sources.flatMap(({ file, root }) =>
  collectFacts(root)
    .filter((f) => f.path)
    .map((f) => {
      const raw = f.path.split('.').reduce((n, k) => (factState(n) !== 'ok' ? n.value : n)?.[k], root);
      return { ...f, file, where: readablePath(root, f.path), value: factState(raw) === 'ok' ? undefined : raw.value };
    }),
);

// ── Console report ──────────────────────────────────────────────────────────
for (const g of GROUPS) {
  const items = facts.filter((f) => f.state === g.state);
  console.log(`\n${g.title} (${items.length}) — ${g.hint}`);
  for (const f of items) console.log(`  • ${f.where}\n      ${f.note}`);
}
const total = facts.length;
console.log(total ? `\n${total} item(s) to resolve. Edit content/school.js, then run npm run build.\n` : '\nNothing left to check.\n');

// ── CONTENT-CHECKLIST.md ────────────────────────────────────────────────────
if (process.argv.includes('--write')) {
  const md = [
    '# Content checklist',
    '',
    'Everything the website still needs from the school. Generated by `npm run checklist` from the',
    '`todo()`, `draft()` and `verify()` markers in `content/school.js`. Do not edit this file by hand:',
    'fix the fact in `content/school.js` and run `npm run checklist` again.',
    '',
    'Most important for university admissions (the School Profile): the official English name,',
    'CEEB code, director and university counselor, curriculum hours, grading scale, whether the',
    'school ranks students, programs not offered, and where graduates enrolled.',
    '',
  ];
  for (const g of GROUPS) {
    const items = facts.filter((f) => f.state === g.state);
    md.push(`## ${g.title} (${items.length})`, '', `_${g.hint}_`, '');
    for (const f of items) {
      md.push(`- [ ] \`${f.where}\` — ${f.note}`);
      const text = preview(f.value);
      if (text) md.push(`  > ${text.length > 240 ? `${text.slice(0, 237)}…` : text}`);
    }
    md.push('');
  }
  await writeFile(join(ROOT, 'CONTENT-CHECKLIST.md'), md.join('\n'));
  console.log('Wrote CONTENT-CHECKLIST.md');
}
